algoritmo "CALCULO DE ÁGUA VS PESO"
//monte um programa que soliceite ao usuario o seu peso.
//o programa deve calcular e apresentar a quantidade de agua, em ml,
//que deve ser ingerida ao longo de um dia. a formula é:
// qtdAgua = peso*0.40


var

peso, qtdagua:real

inicio

escreva("Digite seu peso: ")
leia(peso)

qtdagua <- peso * 0.040
escreval("Voc3 deve ingerir pelo menos ", qtdagua:02:03, " litros de água")


fimalgoritmo
